reset;

/* Istruisce AMPL ad usare CPLEX*/
option solver gurobi;

/* Disabilita il presolutore e attiva analisi di sensitivita' 	*/
option gurobi_options 'outlev=1 mipgap=0.03';

/* Mostra fino alla seconda cifra decimale */
option display_round 2;

model progetto.mod;  
data test.dat;   

solve;


display {j in 1.._nvars}
    (_varname[j],_var[j], _var[j].lb);
    
display {j in 1.._ncons}
    (_conname[j],_con[j].body, _con[j].slack, _con[j].dual);

display z;